"""empty message

Revision ID: 600d8c2ac403
Revises: 1929de321a73
Create Date: 2023-01-06 20:01:58.631493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '600d8c2ac403'
down_revision = '1929de321a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_column('email')
        batch_op.drop_column('classroom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True))
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
